import{a as S,S as q,i}from"./assets/vendor-BK_rxH-O.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))e(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&e(d)}).observe(document,{childList:!0,subtree:!0});function o(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function e(r){if(r.ep)return;r.ep=!0;const s=o(r);fetch(r.href,s)}})();const H="https://pixabay.com/api/",E="51804617-5c5cc92897b27f37b703790c6";async function h(t,n=1){var o;if(t.trim().length===0)throw new Error("Empty query");try{const e=await S.get(H,{params:{key:E,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:n},timeout:1e4});return{hits:e.data.hits,totalHits:e.data.totalHits}}catch(e){const r=(o=e==null?void 0:e.response)==null?void 0:o.status;let s;throw r===403?s="Invalid API key":r===429?s="Rate limit exceeded, try again later":s="Network or server error",new Error(s)}}let f=null;const p=document.querySelector(".gallery"),l=document.querySelector(".loader");function m(){f?f.refresh():f=new q(".gallery a",{captionsData:"alt",captionDelay:250,nav:!0,loop:!0,showCounter:!0})}function g(){m()}function L(t,n=!0){const o=t.map(e=>`
    <li class="card">
      <a href="${e.largeImageURL}" rel="noopener noreferrer">
        <img src="${e.webformatURL}" alt="${e.tags||"image"}" loading="lazy">
      </a>
      <ul class="stats">
        <li><span>Likes</span><span>${e.likes}</span></li>
        <li><span>Views</span><span>${e.views}</span></li>
        <li><span>Comments</span><span>${e.comments}</span></li>
        <li><span>Downloads</span><span>${e.downloads}</span></li>
      </ul>
    </li>`).join("");n?p.insertAdjacentHTML("beforeend",o):p.innerHTML=o,m()}function x(){p.innerHTML=""}function b(){l&&l.classList.remove("hidden")}function w(){l&&l.classList.add("hidden")}function c(){const t=document.querySelector(".hidden-btn");t&&(t.style.display="none")}function v(){const t=document.querySelector(".hidden-btn");t&&(t.style.display="block")}const B=document.querySelector(".form"),M=document.querySelector('[name="search-text"]'),P=document.querySelector(".hidden-btn");let y="",a=1,u=0;B.addEventListener("submit",async t=>{t.preventDefault();const n=M.value.trim();if(n){x(),c(),b(),y=n,a=1;try{const o=await h(y,a),e=o.hits;if(u=o.totalHits,e.length===0){i.info({message:"Sorry, there are no images matching your search query. Please try again!"});return}L(e,!1),g(),u>a*15?v():(c(),i.info({message:"We're sorry, but you've reached the end of search results."}))}catch(o){i.error({message:o.message||"Network or server error"})}finally{w()}}});P.addEventListener("click",async()=>{a+=1,b(),c();try{const t=await h(y,a),n=t.hits;u=t.totalHits,L(n,!0),g(),u>a*15?v():(c(),i.info({message:"We're sorry, but you've reached the end of search results."}));const o=document.querySelector(".card").getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}catch(t){i.error({message:t.message})}finally{w()}});
//# sourceMappingURL=index.js.map
