import{a as b,S as v,i}from"./assets/vendor-BK_rxH-O.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))e(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&e(d)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function e(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const S="https://pixabay.com/api/",q="51804617-5c5cc92897b27f37b703790c6";async function y(t,n=1){var s;if(t.trim().length===0)throw new Error("Empty query");try{const e=await b.get(S,{params:{key:q,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:n},timeout:1e4});return{hits:e.data.hits,totalHits:e.data.totalHits}}catch(e){const r=(s=e==null?void 0:e.response)==null?void 0:s.status;let o;throw r===403?o="Invalid API key":r===429?o="Rate limit exceeded, try again later":o="Network or server error",new Error(o)}}let f=null;const p=document.querySelector(".gallery"),l=document.querySelector(".loader");function x(){f?f.refresh():f=new v(".gallery a",{captionsData:"alt",captionDelay:250,nav:!0,loop:!0,showCounter:!0})}function m(t,n=!0){const s=t.map(e=>`
      <li class="card">
        <a href="${e.largeImageURL}" rel="noopener noreferrer">
          <img src="${e.webformatURL}" alt="${e.tags||"image"}" loading="lazy">
        </a>
        <ul class="stats">
          <li><span>Likes</span><span>${e.likes}</span></li>
          <li><span>Views</span><span>${e.views}</span></li>
          <li><span>Comments</span><span>${e.comments}</span></li>
          <li><span>Downloads</span><span>${e.downloads}</span></li>
        </ul>
      </li>`).join("");n?p.insertAdjacentHTML("beforeend",s):p.innerHTML=s,x()}function B(){p.innerHTML=""}function g(){l&&l.classList.remove("hidden")}function w(){l&&l.classList.add("hidden")}function c(){const t=document.querySelector(".hidden-btn");t&&(t.style.display="none")}function L(){const t=document.querySelector(".hidden-btn");t&&(t.style.display="block")}const H=document.querySelector(".form"),M=document.querySelector('[name="search-text"]'),E=document.querySelector(".hidden-btn");let h="",a=1,u=0;H.addEventListener("submit",async t=>{t.preventDefault();const n=M.value.trim();if(n){B(),c(),g(),h=n,a=1;try{const s=await y(h,a),e=s.hits;if(u=s.totalHits,e.length===0){i.info({message:"Sorry, there are no images matching your search query. Please try again!"});return}m(e,!1),u>a*15?L():(c(),i.info({message:"We're sorry, but you've reached the end of search results."}))}catch(s){i.error({message:s.message||"Network or server error"})}finally{w()}}});E.addEventListener("click",async()=>{a+=1,g(),c();try{const t=await y(h,a),n=t.hits;u=t.totalHits,m(n,!0),u>a*15?L():(c(),i.info({message:"We're sorry, but you've reached the end of search results."}));const s=document.querySelector(".card").getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"}),window.lightbox&&window.lightbox.refresh()}catch(t){i.error({message:t.message})}finally{w()}});
//# sourceMappingURL=index.js.map
